// Generated by CoffeeScript 1.12.7
var User, mongoose, userSchema;

mongoose = require('mongoose');

userSchema = mongoose.Schema({
  username: String,
  email: {
    type: String,
    $p: {
      label: 'E-Mail'
    }
  },
  birthdate: {
    type: Date,
    $p: {
      widgetTemplate: 'D-MM-YYYY',
      display: 'e'
    }

  },
  password: {
    type: String,
    $p: {
      hide: true
    }
  },
  isAdmin: {
    type: Boolean
  },
  tags: {
    type: Array,
    "default": []
  },
  meta: {
    slug: {
      type: String
    },
    thumb: {
      type: String
    },
    settings: {
      type: mongoose.Schema.Types.Mixed
    },
    deepMeta: {
      deepSlug: String
    }
  },
  data: mongoose.Schema.Types.Mixed
});

userSchema.virtual('$pTitle').get(function() {
  return this.username;
});

userSchema.virtual('$pTableRowClass').get(function() {
  if (this.isAdmin) {
    return 'info';
  } else {
    return null;
  }
});

User = mongoose.model('User', userSchema);

User.$p = {
  showAddButton: false,
  showSearchForm: false,
  redirectAfterAddEdit: 'old',
  rowActions: [
    {
      label: 'Articles',
      href: '/articles?conditions[user]={$row.id}'
    }, {
      label: 'Pages',
      href: '/pages?conditions[user]={$row.id}'
    }
  ],
  pageActions: []
};

module.exports = User;
